##
# https://docs.docker.com/reference/compose-file/
#

# https://docs.docker.com/reference/compose-file/services/
services:

  # https://github.com/biotorrents/gazelle
  gazelle:
    build: .
    depends_on:
      - nginx
      - postgres
      - manticore
      - redis
      - plausible
    volumes:
      - .:/gazelle

  # https://hub.docker.com/_/nginx
  nginx:
    image: nginx:stable-alpine
    #restart: always
    volumes:
      - ./utilities/docker/nginx:/etc/nginx/templates
      - .:/var/www/html
    ports:
      - 80:80

  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:17-alpine
    #restart: always
    ports:
      - 5432:5432
    volumes:
      - ./utilities/docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gazelle_development
      - POSTGRES_USER=gazelle_development
      - POSTGRES_PASSWORD=gazelle_development

  db:
    image: postgres
    #restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_DB=gazelle_development
      - POSTGRES_USER=gazelle_development
      - POSTGRES_PASSWORD=gazelle_development

  adminer:
    image: adminer:standalone
    #restart: always
    ports:
      - 8080:8080

  # https://hub.docker.com/r/manticoresearch/manticore
  # this requires a php installation for the config file
  manticore:
    build: ./utilities/docker/manticore
    #restart: always
    ports:
      - 9306:9306
      - 9308:9308
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./utilities/docker/manticore/data:/var/lib/manticore
      - ./utilities/docker/manticore/manticore.conf:/etc/manticoresearch/manticore.conf
    environment:
      - POSTGRES_DB=gazelle_development
      - POSTGRES_USER=gazelle_development
      - POSTGRES_PASSWORD=gazelle_development

  # https://hub.docker.com/_/redis
  redis:
    image: redis:latest
    #restart: always

    # https://hub.docker.com/r/plausible/analytics
  plausible:
    image: plausible/analytics:latest
    #restart: always

    # https://docs.docker.com/reference/compose-file/networks/
networks:
  front-tier:
  back-tier:

    # https://docs.docker.com/reference/compose-file/volumes/
volumes:
  mysql-data:
  pg-data:
  sphinx-data:
