<?php

declare(strict_types=1);

use Firebase\JWT\BeforeValidException;
use Firebase\JWT\ExpiredException;
use Firebase\JWT\JWT;
use Firebase\JWT\Key;
use Firebase\JWT\SignatureInvalidException;

/**
 * scratchpad
 */

$app = Gazelle\App::go();

$tg = new Gazelle\TorrentGroups(1);
!d($tg);exit;

$ror = new Gazelle\ResearchOrganizationRegistry();

#$match = $ror->match("university boston");
#!d($match);exit;



$response = $ror->search("boston");
!d($response);exit;


$data = [
    "id" => $app->dbNew->shortUuid(),
    "rorId" => $response["id"] ?? null,
    "grid" => $response["external_ids"]["GRID"]["preferred"] ?? null,

    "name" => $response["name"] ?? null,
    "acronym" => $response["acronyms"][0] ?? null,
    "established" => $response["established"] ?? null,
    "status" => $response["status"] ?? null,
    "relationships" => json_encode($response["relationships"] ?? null),

    "latitude" => $response["addresses"][0]["lat"] ?? null,
    "longitude" => $response["addresses"][0]["lng"] ?? null,
    "country" => $response["country"]["country_code"] ?? null,
    "state" => $response["addresses"][0]["state_code"] ?? null,
    "city" => $response["addresses"][0]["city"] ?? null,
    "postalCode" => $response["addresses"][0]["postcode"] ?? null,

    "type" => strtolower($response["types"][0] ?? null),
    "homepage" => $response["links"][0] ?? null,
    "wikipedia" => $response["wikipedia_url"] ?? null,
];
#!d($data);

?>

<html>
    <head>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>

     <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
</head>
<body>
     <div id="map" style="height: 20rem;"></div>

     <script>
        var map = L.map('map').setView([ <?= $data["latitude"] ?>, <?= $data["longitude"] ?> ], 10);
        console.log(map);

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
}).addTo(map);

var marker = L.marker([ <?= $data["latitude"] ?>, <?= $data["longitude"] ?> ]).addTo(map);
        </script>
</body>
</html>
<?php

exit;

# public and private keys are expected to be base64 encoded
# the last non-empty line is used so that keys can be generated with sodium_crypto_sign_keypair()
# the secret keys generated by other tools may need to be adjusted to match the input expected by libsodium
$now = time();
$expiresIn = 60 * 60; # 1 hour

$payload = [
    "aud" => $app->env->siteDomain, # audience
    "exp" => $now + $expiresIn, # expiration time
    "iat" => $now, # issued at
    "iss" => $app->env->siteDomain, # issuer
    "jti" => $app->dbNew->shortUuid(), # jwt id
    "nbf" => $now, # not before

    # https://jsonapi.org/format/1.2/#document-meta
    "meta" => [
        "sessionId" => session_id(),
        "userId" => $app->user->core["id"],
    ],
];

$jwt = JWT::encode($payload, $app->env->private("jwtPrivateKey"), "EdDSA");
$response = [
    "accessToken" => $jwt,
    "tokenType" => "Bearer",
    "expiresIn" => $expiresIn,
];
!d($response);

$decoded = JWT::decode($jwt, new Key($app->env->private("jwtPublicKey"), "EdDSA"));
!d($decoded);

#iss 	Issuer 	Identifies principal that issued the JWT.
#sub 	Subject 	Identifies the subject of the JWT.
#aud 	Audience 	Identifies the recipients that the JWT is intended for. Each principal intended to process the JWT must identify itself with a value in the audience claim. If the principal processing the claim does not identify itself with a value in the aud claim when this claim is present, then the JWT must be rejected.
#exp 	Expiration Time 	Identifies the expiration time on and after which the JWT must not be accepted for processing. The value must be a NumericDate:[9] either an integer or decimal, representing seconds past 1970-01-01 00:00:00Z.
#nbf 	Not Before 	Identifies the time on which the JWT will start to be accepted for processing. The value must be a NumericDate.
#iat 	Issued at 	Identifies the time at which the JWT was issued. The value must be a NumericDate.
#jti 	JWT ID 	Case-sensitive unique identifier of the token even among different issuers.
