<?php

declare(strict_types=1);

use Firebase\JWT\BeforeValidException;
use Firebase\JWT\ExpiredException;
use Firebase\JWT\JWT;
use Firebase\JWT\Key;
use Firebase\JWT\SignatureInvalidException;

/**
 * scratchpad
 */

$app = Gazelle\App::go();

throw new Exception("uncaught");

# public and private keys are expected to be base64 encoded
# the last non-empty line is used so that keys can be generated with sodium_crypto_sign_keypair()
# the secret keys generated by other tools may need to be adjusted to match the input expected by libsodium
$now = time();
$expiresIn = 60 * 60; # 1 hour

$payload = [
    "aud" => $app->env->siteDomain, # audience
    "exp" => $now + $expiresIn, # expiration time
    "iat" => $now, # issued at
    "iss" => $app->env->siteDomain, # issuer
    "jti" => $app->dbNew->shortUuid(), # jwt id
    "nbf" => $now, # not before

    # https://jsonapi.org/format/1.2/#document-meta
    "meta" => [
        "sessionId" => session_id(),
        "userId" => $app->user->core["id"],
    ],
];

$jwt = JWT::encode($payload, $app->env->private("jwtPrivateKey"), "EdDSA");
$response = [
    "accessToken" => $jwt,
    "tokenType" => "Bearer",
    "expiresIn" => $expiresIn,
];
!d($response);

$decoded = JWT::decode($jwt, new Key($app->env->private("jwtPublicKey"), "EdDSA"));
!d($decoded);

#iss 	Issuer 	Identifies principal that issued the JWT.
#sub 	Subject 	Identifies the subject of the JWT.
#aud 	Audience 	Identifies the recipients that the JWT is intended for. Each principal intended to process the JWT must identify itself with a value in the audience claim. If the principal processing the claim does not identify itself with a value in the aud claim when this claim is present, then the JWT must be rejected.
#exp 	Expiration Time 	Identifies the expiration time on and after which the JWT must not be accepted for processing. The value must be a NumericDate:[9] either an integer or decimal, representing seconds past 1970-01-01 00:00:00Z.
#nbf 	Not Before 	Identifies the time on which the JWT will start to be accepted for processing. The value must be a NumericDate.
#iat 	Issued at 	Identifies the time at which the JWT was issued. The value must be a NumericDate.
#jti 	JWT ID 	Case-sensitive unique identifier of the token even among different issuers.
