<?php

declare(strict_types=1);

use Firebase\JWT\BeforeValidException;
use Firebase\JWT\ExpiredException;
use Firebase\JWT\JWT;
use Firebase\JWT\Key;
use Firebase\JWT\SignatureInvalidException;

/**
 * scratchpad
 */

 $lazy = new \Illuminate\Support\Collection();
 !d($lazy);exit;

$app = Gazelle\App::go();

$autocomplete = new Gazelle\Autocomplete();
$result = $autocomplete->literature("GeneMania");
d($result);


?>

<html>
    <head>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>

     <link rel="stylesheet" type="text/css" href="/css/vendor/skeleton.min.css">
	<link rel="stylesheet" type="text/css" href="/css/vendor/normalize.min.css">

    <style>
    </style>
</head>
<body>
    <form>
        <input type="text" class="typeahead" style="width: 50rem;">
        <input type="hidden" name="torrentGroups[]">
    </form>

    <div>does it cover?</div>

     <script>
        (() => {
        "use strict";

        var bloodhound = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.whitespace,
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            remote: {
                url: "/scratchAjax",
                prepare: function (query, settings) {
                    settings.url += "?q=" + query;
                    return settings;
                },
            }
        });

        $(".typeahead").typeahead({
            hint: true,
            highlight: true,
            minLength: 3
        }, {
            name: "bloodhound",
            source: bloodhound,
            templates: {
                suggestion: function (item) {
                    let localOrRemote = item.isLocal ? "local" : "remote";
                    return "<div class='result " + localOrRemote + "' data-id='" + item.id + "' data-openalexid='" + item.openAlexId + "'>" + item.text + "</div>";
                },
            }
        });

        $(".typeahead").on("typeahead:select", function(e, selected) {
            console.log(selected);
        });

        })();
        </script>
    </body>
</html>

<?php

exit;

# public and private keys are expected to be base64 encoded
# the last non-empty line is used so that keys can be generated with sodium_crypto_sign_keypair()
# the secret keys generated by other tools may need to be adjusted to match the input expected by libsodium
$now = time();
$expiresIn = 60 * 60; # 1 hour

$payload = [
    "aud" => $app->env->siteDomain, # audience
    "exp" => $now + $expiresIn, # expiration time
    "iat" => $now, # issued at
    "iss" => $app->env->siteDomain, # issuer
    "jti" => $app->dbNew->shortUuid(), # jwt id
    "nbf" => $now, # not before

    # https://jsonapi.org/format/1.2/#document-meta
    "meta" => [
        "sessionId" => session_id(),
        "userId" => $app->user->core["id"],
    ],
];

$jwt = JWT::encode($payload, $app->env->private("jwtPrivateKey"), "EdDSA");
$response = [
    "accessToken" => $jwt,
    "tokenType" => "Bearer",
    "expiresIn" => $expiresIn,
];
!d($response);

$decoded = JWT::decode($jwt, new Key($app->env->private("jwtPublicKey"), "EdDSA"));
!d($decoded);

#iss 	Issuer 	Identifies principal that issued the JWT.
#sub 	Subject 	Identifies the subject of the JWT.
#aud 	Audience 	Identifies the recipients that the JWT is intended for. Each principal intended to process the JWT must identify itself with a value in the audience claim. If the principal processing the claim does not identify itself with a value in the aud claim when this claim is present, then the JWT must be rejected.
#exp 	Expiration Time 	Identifies the expiration time on and after which the JWT must not be accepted for processing. The value must be a NumericDate:[9] either an integer or decimal, representing seconds past 1970-01-01 00:00:00Z.
#nbf 	Not Before 	Identifies the time on which the JWT will start to be accepted for processing. The value must be a NumericDate.
#iat 	Issued at 	Identifies the time at which the JWT was issued. The value must be a NumericDate.
#jti 	JWT ID 	Case-sensitive unique identifier of the token even among different issuers.
