##
# https://wiki.nginx.org/Configuration
# https://wiki.nginx.org/Pitfalls
# https://wiki.nginx.org/QuickStart
#

server {
	listen 80 default_server; # ipv4
	listen [::]:80 default_server; # ipv6

	root /var/www/public;
	index.html index.htm index.php;

	# https://www.rfc-editor.org/rfc/rfc2606.txt
	server_name gazelle.test;

	# https://docs.nginx.com/nginx/admin-guide/monitoring/logging/
	access_log off;
	error_log logs/error.log;

	# todo: figure out how to run the container in production
	ssl_certificate /etc/letsencrypt/live/torrents.bio/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/torrents.bio/privkey.pem;

	# torrent file upload fix
	client_max_body_size 4M;

	# https://docs.flightphp.com/en/v3/install
	location / {
		try_files $uri $uri/ /index.php;
	}

	location /public/ {
		return 301 /$request_uri;
	}

	# https://github.com/OPSnet/Gazelle/blob/master/misc/docker/web/nginx.conf
	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		try_files $fastcgi_script_name @missing;
		set $path_info $fastcgi_path_info;
		fastcgi_param PATH_INFO $path_info;
		fastcgi_param HTTP_AUTHORIZATION $http_authorization;
		fastcgi_pass unix:/var/run/php/php-fpm.sock;
		fastcgi_index index.php;
		include fastcgi.conf;

		# https://httpoxy.org
		fastcgi_param HTTP_PROXY "";
	}

	location @missing {
		fastcgi_pass unix:/var/run/php/php-fpm.sock;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		set $path_info $fastcgi_path_info;
		fastcgi_param PATH_INFO $path_info;
		fastcgi_param HTTP_AUTHORIZATION $http_authorization;
		fastcgi_index index.php;
		include fastcgi.conf;
		fastcgi_param SCRIPT_FILENAME "${document_root}/index.php";

		# https://httpoxy.org
		fastcgi_param HTTP_PROXY "";
	}

	location ~* ^.+\.(js|css)$ {
		expires -1;
	}

	# https://nginx.org/en/docs/http/ngx_http_access_module.html
	location ^~ /.git/ {
		deny all;
	}

	location ^~ /config/private.php {
		deny all;
	}

	# https://geekflare.com/cybersecurity/nginx-webserver-security-hardening-guide/
	if ($request_method !~ ^(GET|HEAD|POST|PATCH|DELETE)$ ) { # https://jsonapi.org/format/#crud
		return 405; 
	}
}