##
# https://cheatsheetseries.owasp.org/cheatsheets/PHP_Configuration_Cheat_Sheet.html
#

## PHP error handling ##
expose_php = Off
error_reporting = E_ALL
display_errors = Off
display_startup_errors = Off
log_errors = On
ignore_repeated_errors = Off

## PHP general settings ##
allow_url_include = Off
variables_order = "GPCS"
allow_webdav_methods = Off
session.gc_maxlifetime = 600

## PHP file upload handling ##
file_uploads = On
upload_max_filesize = 4M
max_file_uploads = 2

## PHP executable handling ##
enable_dl = Off
disable_functions = system, shell_exec, passthru, show_source, highlight_file, proc_open, fopen_with_path, dbmopen, dbase_open, move_uploaded_file, filepro, filepro_rowcount, filepro_retrieve, posix_mkfifo
#disable_functions = system, exec, shell_exec, passthru, phpinfo, show_source, highlight_file, popen, proc_open, fopen_with_path, dbmopen, dbase_open, putenv, move_uploaded_file, chdir, mkdir, rmdir, chmod, rename, filepro, filepro_rowcount, filepro_retrieve, posix_mkfifo
disable_classes =

## PHP session handling ##
session.name = gazelle
session.auto_start = Off
session.use_trans_sid = 0
session.cookie_domain = gazelle.test
session.use_strict_mode = 1
session.use_cookies = 1
session.use_only_cookies = 1
session.cookie_lifetime = 14400
session.cookie_secure = 1
session.cookie_httponly = 1
session.cookie_samesite = Strict
session.cache_expire = 30

## Some more security paranoid checks ##
memory_limit = 50M
post_max_size = 20M
max_execution_time = 60
report_memleaks = On
html_errors = Off
zend.exception_ignore_args = On


##
# https://github.com/jvoisin/snuffleupagus/blob/master/config/snuffleupagus.ini
#

sp.configuration_file=/etc/php/conf.d/default_php8.rules
sp.configuration_file=/etc/php/conf.d/detect_dangerous_extensions.rules
sp.configuration_file=/etc/php/conf.d/ini_protection.rules
